### ISSUE TITLE
Move over to using parameters

### ISSUE THREAD

**Issue by ravensorb** [mahdi22/linux_joindomain#2]
Any thoughts to moving this over to using parameters?  

Ex: right now, proxy server is set in such a way that they only option to disable is to remove the references.

**Comment by mahdi22** [comment]
thank you for your remark. I think that you have right, use a parameter to enable or disable proxy is better than delete it manually. I will add this functionality in the next commit.
If you have an other remark don't hesitate.

**Comment by ravensorb** [comment]
That would be great.  Two other ideas might be -- a variable for the homedir string (I tend to use /home/%d/%u a lot) and also if only the domain variable passed it, use that for the workgroup and realm (including adjusting for upper and lower case requirements).  Thoughts? 

Edited - might also be nice to be able to add specific groups to the sudo list?

**Comment by mahdi22** [comment]
Repo updated
Use of proxy is now optional, you can enable or disable it using the use_proxy variable. Please read the Readme
