### ISSUE TITLE
Add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by ktinthecloud** [mahdi22/linux_joindomain#8]
Please add a Debian-24.yml file under /vars with the same packages that are in Debian-22.yml to add support for Ubuntu 24.04.  I have tested this, and it works.  I'd open up a PR myself, but don't have access.  Thanks.

**Comment by ktinthecloud** [comment]
Never mind, figured out how to submit a pull request from forked repo.  PR is here: https://github.com/mahdi22/linux_joindomain/pull/9

**Comment by mahdi22** [comment]
Hello,
Thank you for your participation. Your requedt is merged
